# Generated by Django 5.2.6 on 2025-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='completed_test',
            field=models.BooleanField(default=False),
        ),
    ]
