# Generated by Django 5.2.1 on 2025-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quizattempt_completed_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
