# Generated by Django 5.2.1 on 2025-09-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_courseitem_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
