# Generated by Django 5.2.1 on 2025-10-06 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lms', '0047_alter_coursebulletpoint_options_and_more'),
        ('quiz', '0012_alter_courseitem_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='courseitem',
            options={'ordering': ['order'], 'verbose_name': 'Course Item', 'verbose_name_plural': 'Course Items'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['order'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'verbose_name': 'Quiz Attempt', 'verbose_name_plural': 'Quiz Attempts'},
        ),
        migrations.AlterModelOptions(
            name='quizprogress',
            options={'verbose_name': 'Quiz Progress', 'verbose_name_plural': 'Quiz Progresses'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Answer', 'verbose_name_plural': 'User Answers'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseitems', to='lms.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.coursesection', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('Radio', 'Radio')], default='MCQ', max_length=50, null=True, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_for_course', to='lms.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lms.coursesection', verbose_name='Course Section'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_test',
            field=models.BooleanField(default=False, verbose_name='Completed Test'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished At'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='answered_questions',
            field=models.JSONField(default=list, verbose_name='Answered Questions'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='current_question_index',
            field=models.IntegerField(default=0, verbose_name='Current Question Index'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz.quizattempt', verbose_name='Quiz Attempt'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='chosen_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.choice', verbose_name='Chosen Option'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
