# Generated by Django 5.2.1 on 2025-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0033_review_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='page_type',
            field=models.CharField(blank=True, choices=[('basic_page', 'Главный'), ('about_page', 'О нас')], max_length=50, null=True),
        ),
    ]
