# Generated by Django 5.2.1 on 2025-09-18 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0035_blogtype_pagetype_alter_blogs_blog_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_type_blogs', to='lms.blogs'),
        ),
        migrations.AddField(
            model_name='pagetype',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_type_blogs', to='lms.blogs'),
        ),
    ]
