# Generated by Django 5.2.1 on 2025-09-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0036_blogtype_course_pagetype_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtype',
            name='course',
        ),
        migrations.RemoveField(
            model_name='pagetype',
            name='course',
        ),
    ]
