# Generated by Django 5.2.1 on 2025-09-18 15:54

import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_remove_blogtype_course_remove_pagetype_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/', validators=[lms.models.validate_image_format, lms.models.validate_image_size_image]),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/', validators=[lms.models.validate_image_format, lms.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='tutors/', validators=[lms.models.validate_image_format, lms.models.validate_image_tutor_size]),
        ),
    ]
