# Generated by Django 5.2.1 on 2025-09-18 16:02

import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0038_alter_course_course_image_alter_course_preview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/images/', validators=[lms.models.validate_image_format, lms.models.validate_image_article_size]),
        ),
    ]
