# Generated by Django 5.2.6 on 2025-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0040_course_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.TextField(default='', help_text='Paste full Vimeo embed code here'),
        ),
    ]
