# Generated by Django 5.2.6 on 2025-09-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0041_alter_lecture_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(),
        ),
    ]
