# Generated by Django 5.2.1 on 2025-09-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0043_lectureprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='payment_period',
        ),
        migrations.RemoveField(
            model_name='course',
            name='payment_period_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='payment_period_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='payment_period_uz',
        ),
    ]
