# Generated by Django 5.2.1 on 2025-09-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0044_remove_course_payment_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subtitle_uz',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='content_uz',
        ),
    ]
