# Generated by Django 5.2.1 on 2025-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0045_remove_course_subtitle_remove_course_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
