# Generated by Django 5.2.1 on 2025-10-06 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0046_alter_coursesection_options_alter_lecture_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursebulletpoint',
            options={'verbose_name': 'Course Bullet Point', 'verbose_name_plural': 'Course Bullet Points'},
        ),
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ['order'], 'verbose_name': 'Course Section', 'verbose_name_plural': 'Course Sections'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['order'], 'verbose_name': 'Lecture', 'verbose_name_plural': 'Lectures'},
        ),
        migrations.AlterModelOptions(
            name='lectureprogress',
            options={'verbose_name': 'Lecture Progress', 'verbose_name_plural': 'Lecture Progresses'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name': 'Qualification', 'verbose_name_plural': 'Qualifications'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutors'},
        ),
        migrations.AlterModelOptions(
            name='usercourses',
            options={'verbose_name': 'User Course', 'verbose_name_plural': 'User Courses'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='end_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='End Hour'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text1',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text1_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text1_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text1_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text2',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text2_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text3',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text3_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text3_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='helper_text3_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='organiser_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Organiser Email'),
        ),
        migrations.AlterField(
            model_name='article',
            name='organiser_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organiser Full Name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='organiser_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Organiser Phone'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Hour'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.blogtype', verbose_name='Blog Type'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text1',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text1_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text1_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text1_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text2',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text2_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text3',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text3_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text3_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text3_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text4',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 4'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text4_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 4'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text4_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 4'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text4_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 4'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text5',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 5'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text5_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 5'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text5_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 5'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='helper_text5_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 5'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='page_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.pagetype', verbose_name='Page Type'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='vimeo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Vimeo URL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Main Course Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_preview',
            field=models.BooleanField(default=False, verbose_name='Is Preview'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview_en',
            field=models.TextField(blank=True, null=True, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Preview Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.TextField(blank=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lms.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='vimeo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Vimeo URL'),
        ),
        migrations.AlterField(
            model_name='coursebulletpoint',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='lms.coursesection', verbose_name='Course Section'),
        ),
        migrations.AlterField(
            model_name='coursebulletpoint',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='coursebulletpoint',
            name='text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='coursebulletpoint',
            name='text_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='coursebulletpoint',
            name='text_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lms.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.DurationField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lms.coursesection', verbose_name='Course Section'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lecture', verbose_name='Lecture'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='watched_percent',
            field=models.FloatField(default=0, verbose_name='Watched Percent'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='watched_seconds',
            field=models.FloatField(default=0, verbose_name='Watched Seconds'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.CharField(max_length=200, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_qualifications', to='lms.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_uz',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lms.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='show',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Show on site'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='experience_years',
            field=models.PositiveIntegerField(verbose_name='Experience (Years)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text1',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text1_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text1_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text1_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 1'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text2',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text2_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 2'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text3',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text3_en',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text3_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='helper_text3_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text 3'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Hourly Rate'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='lessons_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Lessons Completed'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='tutors/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='social_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='social_linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='social_twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subject_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
