# Generated by Django 5.2.6 on 2025-10-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0047_alter_coursebulletpoint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
