# Generated by Django 5.2.6 on 2025-10-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0048_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outcomes',
            field=models.TextField(blank=True, null=True, verbose_name='What Will You Achieve?'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, null=True, verbose_name='Syllabus'),
        ),
    ]
