# Generated by Django 5.2.6 on 2025-10-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0049_course_outcomes_course_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outcomes_en',
            field=models.TextField(blank=True, null=True, verbose_name='What Will You Achieve?'),
        ),
        migrations.AddField(
            model_name='course',
            name='outcomes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='What Will You Achieve?'),
        ),
        migrations.AddField(
            model_name='course',
            name='outcomes_uz',
            field=models.TextField(blank=True, null=True, verbose_name='What Will You Achieve?'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_en',
            field=models.TextField(blank=True, null=True, verbose_name='Syllabus'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Syllabus'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Syllabus'),
        ),
    ]
