# Generated by Django 5.2.6 on 2025-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0051_alter_course_syllabus_alter_course_syllabus_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus_en',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus_ru',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus_uz',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
